Add files via upload

diff --git a/services b/services
--- a/services
+++ b/services
@@ -29,7 +29,7 @@
 #  Geovanni B.R. (geobarrod) <igeo.cu@gmail.com>, 2026-01-05
 #  Improvements to the original service(8) command to allow multiple services
 #  management in a single invocation. Supported actions include:
-#  configtest, disable, enable, extracommands, forceconfigtest, forceextracommands, forcegracefulstop,
+#  configtest, disable, enable, enabled, extracommands, forceconfigtest, forceextracommands, forcegracefulstop,
 #  forcepoll. forcercvar, forcereload, forcerestart, forcestart, forcestatus, forcestop, forceupgrade,
 #  gracefulstop, oneconfigtest, oneextracommands, onegracefulstop, onepoll. onercvar, onereload, onerestart,
 #  onestart, onestatus, onestop, oneupgrade, poll. rcvar, reload, restart, start, status, stop, upgrade.
@@ -44,7 +44,7 @@ usage () {
     echo "${0##*/} [-j <jail name or id>] [-q] -R"
     echo "${0##*/} [-j <jail name or id>] [-v] -l"
     echo "${0##*/} [-j <jail name or id>] [-v] -r"
-    echo "${0##*/} [-dqv] [-E var=value] <rc.d script> start|stop|etc."
+    echo "${0##*/} [-j <jail name or id>] [-dqv] [-E var=value] <rc.d script> start|stop|etc."
     echo "${0##*/} <action> <service1> [service2 ...]"
     echo "${0##*/} -h"
     echo ''
@@ -52,8 +52,8 @@ usage () {
     echo "-j                Perform actions within the named jail"
     echo "-E n=val          Set variable n to val before executing the rc.d script"
     echo "-e                Show services that are enabled"
-    echo "-R                Stop and start enabled $local_startup services"
-    echo "-l                List all scripts in /etc/rc.d and $local_startup"
+    echo "-R                Stop and start enabled \$local_startup services"
+    echo "-l                List all scripts in /etc/rc.d and \$local_startup"
     echo "-r                Show the results of boot time rcorder"
     echo "-q                Quiet"
     echo "-v                Verbose"
@@ -78,6 +78,8 @@ done
 shift $(( $OPTIND - 1 ))
 
 if [ -n "${JAIL}" ]; then
+    # We need to rebuild the command line before passing it on.
+    # We do not send the -j argument into the jail.
     args=""
     [ -n "${ENABLED}" ] && args="${args} -e"
     [ -n "${LIST}" ] && args="${args} -l"
@@ -88,101 +90,217 @@ if [ -n "${JAIL}" ]; then
     for var in ${VARS}; do
         args="${args} -E ${var}"
     done
+
+    # Call jexec(8) with the rebuild args and any positional args that
+    # were left in $@
     /usr/sbin/jexec -l "${JAIL}" /usr/sbin/service $args "$@"
     exit $?
 fi
 
-if [ -n "$DEBUG" ]; then
-    VARS="${VARS} rc_debug=yes"
+[ -n "$DEBUG" ] && VARS="${VARS} rc_debug=yes"
+
+if [ -n "$RESTART" ]; then
+    skip="-s nostart"
+    if [ `/sbin/sysctl -n security.jail.jailed` -eq 1 ]; then
+        skip="$skip -s nojail"
+        if [ `/sbin/sysctl -n security.jail.vnet` -ne 1 ]; then
+            skip="$skip -s nojailvnet"
+        fi
+    fi
+    [ -n "$local_startup" ] && find_local_scripts_new
+    files=`rcorder ${skip} ${local_rc} 2>/dev/null`
+
+    for file in `reverse_list ${files}`; do
+        if grep -q ^rcvar $file; then
+            eval `grep ^name= $file`
+            eval `grep ^rcvar $file`
+            if [ -n "$rcvar" ]; then
+                load_rc_config_var ${name} ${rcvar}
+            fi
+            if [ -n "$QUIET" ]; then
+                checkyesno $rcvar 2>/dev/null && run_rc_script ${file} stop >/dev/null 2>&1
+            else
+                checkyesno $rcvar 2>/dev/null && run_rc_script ${file} stop
+            fi
+        fi
+    done
+    for file in $files; do
+        if grep -q ^rcvar $file; then
+            eval `grep ^name= $file`
+            eval `grep ^rcvar $file`
+            if [ -n "$QUIET" ]; then
+                checkyesno $rcvar 2>/dev/null && run_rc_script ${file} start >/dev/null 2>&1
+            else
+                checkyesno $rcvar 2>/dev/null && run_rc_script ${file} start
+            fi
+        fi
+    done
+    exit 0
 fi
 
-# --- main logic for multiple services ---
-
-if [ $# -lt 1 ]; then
-    usage
-    exit 1
+if [ -n "$ENABLED" -o -n "$RCORDER" ]; then
+    # Copied from /etc/rc
+    skip="-s nostart"
+    if [ `/sbin/sysctl -n security.jail.jailed` -eq 1 ]; then
+        skip="$skip -s nojail"
+        if [ `/sbin/sysctl -n security.jail.vnet` -ne 1 ]; then
+            skip="$skip -s nojailvnet"
+        fi
+    fi
+    [ -n "$local_startup" ] && find_local_scripts_new
+    files=`rcorder ${skip} /etc/rc.d/* ${local_rc} 2>/dev/null`
 fi
 
-first=$1
-shift
+if [ -n "$ENABLED" ]; then
+    for file in $files; do
+        if grep -q ^rcvar $file; then
+            eval `grep ^name= $file`
+            eval `grep ^rcvar $file`
+            if [ -n "$rcvar" ]; then
+                load_rc_config_var ${name} ${rcvar}
+            fi
+            checkyesno $rcvar 2>/dev/null && echo $file
+        fi
+    done
+    exit 0
+fi
 
-actions="
-configtest disable enable extracommands forceconfigtest forceextracommands forcegracefulstop
+if [ -n "$LIST" ]; then
+    for dir in /etc/rc.d $local_startup; do
+        [ -n "$VERBOSE" ] && echo "From ${dir}:"
+        [ -d ${dir} ] && /bin/ls -1 ${dir}
+    done
+    exit 0
+fi
+
+if [ -n "$RCORDER" ]; then
+    for file in $files; do
+        echo $file
+        if [ -n "$VERBOSE" ]; then
+            case "$file" in
+            */${early_late_divider})
+                echo '========= Early/Late Divider =========' ;;
+            esac
+        fi
+    done
+    exit 0
+fi
+
+# --- Unified logic for multiple services ---
+[ $# -lt 1 ] && { usage; exit 1; }
+
+ACTIONS="
+configtest disable enable enabled extracommands forceconfigtest forceextracommands forcegracefulstop
 forcepoll forcercvar forcereload forcerestart forcestart forcestatus forcestop forceupgrade
 gracefulstop oneconfigtest oneextracommands onegracefulstop onepoll onercvar onereload onerestart
 onestart onestatus onestop oneupgrade poll rcvar reload restart start status stop upgrade
 "
 
-is_action=0
-for a in $actions; do
-    if [ "$first" = "$a" ]; then
-        is_action=1
-        break
+first=$1
+last=${!#}
+
+is_action_first=0
+is_action_last=0
+
+for a in $ACTIONS; do
+    [ "$first" = "$a" ] && is_action_first=1 && break
+done
+if [ $is_action_first -eq 0 ]; then
+    for a in $ACTIONS; do
+        [ "$last" = "$a" ] && is_action_last=1 && break
+    done
+fi
+
+scripts=""
+action=""
+extra_args=""
+
+if [ $is_action_first -eq 1 ]; then
+    action=$first
+    shift
+    [ $# -lt 1 ] && { echo "No services specified"; exit 1; }
+    scripts="$@"
+elif [ $is_action_last -eq 1 ]; then
+    action=$last
+    set -- "${@:1:$(($#-1))}"
+    [ $# -lt 1 ] && { echo "No services specified"; exit 1; }
+    scripts="$@"
+else
+    script=$first
+    shift
+    [ $# -lt 1 ] && { usage; exit 1; }
+    action=$1
+    shift
+    scripts="$script"
+    extra_args="$@"
+fi
+
+run_service_action () {
+    _script="$1"
+    _action="$2"
+    shift 2
+    _extra="$@"
+
+    case "$_action" in
+        enable)
+            echo "Enabling ${_script} in rc.conf"
+            sysrc "${_script}_enable=YES"
+            ;;
+        disable)
+            echo "Disabling ${_script} in rc.conf"
+            sysrc "${_script}_enable=NO"
+            ;;
+        *)
+            found=0
+            for dir in /etc/rc.d ${local_startup:-/usr/local/etc/rc.d}; do
+                if [ -x "$dir/$_script" ]; then
+                    [ -n "$VERBOSE" ] && echo "$_script is located in $dir"
+                    if [ -n "$QUIET" ]; then
+                        /usr/bin/env -i HOME=/ PATH=/sbin:/bin:/usr/sbin:/usr/bin ${VARS} "$dir/$_script" "$_action" $_extra > /dev/null 2>&1
+                    else
+                        /usr/bin/env -i HOME=/ PATH=/sbin:/bin:/usr/sbin:/usr/bin ${VARS} "$dir/$_script" "$_action" $_extra
+                    fi
+                    found=1
+                    break
+                fi
+            done
+            [ $found -eq 0 ] && echo "$_script not found in /etc/rc.d or local startup"
+            ;;
+    esac
+}
+
+if [ -n "$extra_args" ]; then
+    run_service_action "$scripts" "$action" $extra_args
+else
+    for s in $scripts; do
+        run_service_action "$s" "$action"
+    done
+fi
+
+exit 0
+
+# --- Classic single-service execution ---
+if [ $# -gt 0 ]; then
+    script=$1
+    shift
+else
+    usage
+    exit 1
+fi
+
+cd /
+for dir in /etc/rc.d $local_startup; do
+    if [ -x "$dir/$script" ]; then
+        [ -n "$VERBOSE" ] && echo "$script is located in $dir"
+        if [ -n "$QUIET" ]; then
+            exec /usr/bin/env -i -L -/daemon HOME=/ PATH=/sbin:/bin:/usr/sbin:/usr/bin ${VARS} "$dir/$script" "$@" > /dev/null 2>&1
+        else
+            exec /usr/bin/env -i -L -/daemon HOME=/ PATH=/sbin:/bin:/usr/sbin:/usr/bin ${VARS} "$dir/$script" "$@"
+        fi
     fi
 done
 
-if [ $is_action -eq 1 ]; then
-    # New syntax: action first, then multiple services
-    action=$first
-    if [ $# -lt 1 ]; then
-        echo "No services specified"
-        exit 1
-    fi
-    for script in "$@"; do
-        if [ "$action" = "enable" ]; then
-            echo "Enabling $script in rc.conf"
-            sysrc "${script}_enable=YES"
-            continue
-        elif [ "$action" = "disable" ]; then
-            echo "Disabling $script in rc.conf"
-            sysrc "${script}_enable=NO"
-            continue
-        fi
-        found=0
-        for dir in /etc/rc.d $local_startup; do
-            if [ -x "$dir/$script" ]; then
-                [ -n "$VERBOSE" ] && echo "$script is located in $dir"
-                if [ -n "$QUIET" ]; then
-                    /usr/bin/env -i -L -/daemon HOME=/ PATH=/sbin:/bin:/usr/sbin:/usr/bin ${VARS} "$dir/$script" "$action" > /dev/null 2>&1
-                else
-                    /usr/bin/env -i -L -/daemon HOME=/ PATH=/sbin:/bin:/usr/sbin:/usr/bin ${VARS} "$dir/$script" "$action"
-                fi
-                found=1
-                break
-            fi
-        done
-        if [ $found -eq 0 ]; then
-            echo "$script does not exist in /etc/rc.d or the local startup directories (${local_startup}), or is not executable"
-        fi
-    done
-else
-    # Classic syntax: service first, then action
-    script=$first
-    if [ $# -lt 1 ]; then
-        usage
-        exit 1
-    fi
-    action=$1
-    shift
-    if [ "$action" = "enable" ]; then
-        echo "Enabling $script in rc.conf"
-        sysrc "${script}_enable=YES"
-        exit 0
-    elif [ "$action" = "disable" ]; then
-        echo "Disabling $script in rc.conf"
-        sysrc "${script}_enable=NO"
-        exit 0
-    fi
-    for dir in /etc/rc.d $local_startup; do
-        if [ -x "$dir/$script" ]; then
-            [ -n "$VERBOSE" ] && echo "$script is located in $dir"
-            if [ -n "$QUIET" ]; then
-                exec /usr/bin/env -i -L -/daemon HOME=/ PATH=/sbin:/bin:/usr/sbin:/usr/bin ${VARS} "$dir/$script" "$action" "$@" > /dev/null 2>&1
-            else
-                exec /usr/bin/env -i -L -/daemon HOME=/ PATH=/sbin:/bin:/usr/sbin:/usr/bin ${VARS} "$dir/$script" "$action" "$@"
-            fi
-        fi
-    done
-    echo "$script does not exist in /etc/rc.d or the local startup directories (${local_startup}), or is not executable"
-    exit 1
-fi
+# If the script was not found
+echo "$script does not exist in /etc/rc.d or the local startup"
+echo "directories (${local_startup}), or is not executable"
+exit 1
